### ISSUE TITLE
Can't use the PRIVATE part of api

### ISSUE THREAD

**Issue by JustinNothling** [krystianity/node-bitstamp#30]
UnhandledPromiseRejectionWarning: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:183:11)
    at new Buffer (buffer.js:158:17)
    at Signature._createSignature (/Users/justinnothling/Code/nibit/node_modules/node-bitstamp/lib/Signature.js:52:52)
    at Signature.signBody (/Users/justinnothling/Code/nibit/node_modules/node-bitstamp/lib/Signature.js:75:41)
    at Bitstamp._getOptions (/Users/justinnothling/Code/nibit/node_modules/node-bitstamp/lib/Bitstamp.js:68:39)
    at Promise (/Users/justinnothling/Code/nibit/node_modules/node-bitstamp/lib/Bitstamp.js:90:34)
    at Promise._execute (/Users/justinnothling/Code/nibit/node_modules/node-bitstamp/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/Users/justinnothling/Code/nibit/node_modules/node-bitstamp/node_modules/bluebird/js/release/promise.js:488:18)
    at new Promise (/Users/justinnothling/Code/nibit/node_modules/node-bitstamp/node_modules/bluebird/js/release/promise.js:79:10)
    at Bitstamp.call (/Users/justinnothling/Code/nibit/node_modules/node-bitstamp/lib/Bitstamp.js:79:16)
    at Bitstamp.balance (/Users/justinnothling/Code/nibit/node_modules/node-bitstamp/lib/Bitstamp.js:198:21)
    at test (/Users/justinnothling/Code/nibit/bitesting.js:23:36)
    at Object.<anonymous> (/Users/justinnothling/Code/nibit/bitesting.js:40:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

**Comment by JustinNothling** [comment]
Can anyone help me understand what I'm doing wrong?

**Comment by JustinNothling** [comment]
never mind, I was being dumb
